name = "LAC"
defaultTargets = ["Lectures", "Proofs"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "Proofs" 

[[lean_lib]]
name = "Lectures" 
